### ISSUE TITLE
End user Struggles

### ISSUE THREAD

**Issue by JoshSummerTop** [BoxcarsAI/boxcars#111]
I know this is a new project. But in terms of out of box functionality pertaining to Active Records connection, I personally would appreciate more documentation and effort. I think this is the best package at that in this stage. Especially pertaining to tabular data. One thing to consider is that a lot of junior or mid term devs might be looking at this library.
What do you need to keep the project going at full force.

This is not a code specific ask.

**Comment by francis** [comment]
Hi @JoshSummerTop - I am actively using this project in a few other projects, but have not been making many changes. I can add more documentation for you on the Active Record front.

**Comment by JoshSummerTop** [comment]
@francis that would be awesome, when you have the time.

**Comment by JoshSummerTop** [comment]
The only other issue I have, other than focus on the ActiveRecords front is how one might make a call back to produce the results outside of the chat. From what I understand the results will be scoped to the chat as a string. Is there a way to change the results outside of the chat, without using eval.

**Comment by francis** [comment]
On a Boxcar, the *conduct* method returns a Result that includes the code to be run.

https://rubydoc.info/gems/boxcars/Boxcars/Boxcar#conduct-instance_method
