### ISSUE TITLE
OpenBSD system example

### ISSUE THREAD

**Issue by basicfeatures** [BoxcarsAI/boxcars#124]
> Note: We are actively seeking ways to improve our system's ability to identify and prevent any nefarious attempts from occurring. If you have any suggestions or recommendations, please feel free to share them with us by either finding an existing issue or creating a new one and providing us with your feedback.

OpenBSD: https://gist.github.com/basicfeatures/7d1448aad6fadc0def4ffee443f26dab

Hope it finds y'all well!

**Comment by francis** [comment]
nothing to do with the gem
