### ISSUE TITLE
Notion Q&A

### ISSUE THREAD

**Issue by francis** [BoxcarsAI/boxcars#13]
This would be pretty slick to pull off. https://github.com/hwchase17/notion-qa

**Comment by jaigouk** [comment]
it is using faiss store and there is a ruby gem for that already 
https://github.com/ankane/faiss-ruby

**Comment by jaigouk** [comment]
the notion-qa example repo is using faiss and ruby but I was not able to find a good usage examples.

https://github.com/ankane/faiss-ruby
https://rubygems.org/gems/faiss/reverse_dependencies 

i will try to use existing Hnswlib and check the [hwchase17/notion-qa](https://github.com/hwchase17/notion-qa)

**Comment by francis** [comment]
Thanks @jaigouk 👍
