### ISSUE TITLE
The class name in the sample code of BoxCar-Google-Search wiki has not been changed.

### ISSUE THREAD

**Issue by KurisakiRyohei** [BoxcarsAI/boxcars#50]
I found that the class name in the sample code of BoxCar-Google-Search [wiki](https://github.com/BoxcarsAI/boxcars/wiki/BoxCar-Google-Search) has not been changed, and I believe that the sample code in the wiki needs to be updated as well, as it was renamed in the following commit: https://github.com/BoxcarsAI/boxcars/commit/753d9a10b2f8dee970fdf8c6c6f8a9b2e029c614.

**Comment by francis** [comment]
Thanks for fixing this. Merge applied.
