### ISSUE TITLE
Chore: reduce the number of markdown files in Notion DB folder

### ISSUE THREAD

**Issue by jaigouk** [BoxcarsAI/boxcars#56]
this is just for testing / playing purpose. we don't need to keep all those files in the repo.

**Comment by jaigouk** [comment]
I will create a PR to clean up. Again, thanks for accept the PR.

**Comment by francis** [comment]
Thanks in advance @jaigouk

**Comment by jaigouk** [comment]
sorry for late reponse. i will check this in this weekend
