### ISSUE TITLE
demo rails app

### ISSUE THREAD

**Issue by estiens** [BoxcarsAI/boxcars#57]
It would be very handy to have a demo rails app (reasonably complicated date but not that much so) that can be cloned/seeded/and shows various examples of boxcar integrations  - if this isn't on the roadmap I might be able to take it on to try to sell boxcars to a few prospective folks that might have a use for it - by sell I mean convince to use it :P

**Comment by tabrez-syed** [comment]
Awesome! We have the beginnings of one using the https://github.com/ralixjs/rails-ralix-tailwind that we can use. Are you open to connecting so we can discuss it further? You can write in at hi@boxcars.ai

**Comment by estiens** [comment]
Sure, I'll ping you if/when I can commit to doing some work on it! or if work on it proceeds in the meantime, happy to throw in some PRs at some point
