### ISSUE TITLE
Getting started docs out of date

### ISSUE THREAD

**Issue by beouk** [BoxcarsAI/boxcars#58]
Getting started doc references `Boxcars::Serp.new` when I believe this should be `Boxcars::GoogleSearch.new`

[https://github.com/BoxcarsAI/boxcars/wiki/Getting-Started](https://github.com/BoxcarsAI/boxcars/wiki/Getting-Started)

**Comment by francis** [comment]
I just updated and added the latest boxcars and newest engine to the list. Thanks for pointing this out! 👍
