### ISSUE TITLE
boxcar for vector search

### ISSUE THREAD

**Issue by francis** [BoxcarsAI/boxcars#60]
Now that we have embedded vector search, add a boxcar that scans search results and gives a coherent summary.

Ideally, the class would be Boxcars::VectorSearch

@jaigouk - your new additions will enable this. I want to accept the default in-memory vector store that you provided or external (Posgresql, Redis, Pinecone, ...) stores.

**Comment by mculp** [comment]
Can take a cue from AutoGPT. Here's their setup: https://github.com/Significant-Gravitas/Auto-GPT/tree/master/autogpt/memory

**Comment by francis** [comment]
👍  Great idea @mculp - I will study this approach as it solves another problem I was considering too.

**Comment by jaigouk** [comment]
@francis 
https://github.com/BoxcarsAI/boxcars/pull/74 is using `Boxcars::VectorStore::Document` for building vectore stores and search results and `Boxcars::VectorStore::Document` has content, embedding and metadata. Can we close this ticket?

**Comment by jaigouk** [comment]
can we mark this issue as done? https://github.com/BoxcarsAI/boxcars/pull/92 is merged.
