### ISSUE TITLE
meta data with vector store

### ISSUE THREAD

**Issue by francis** [BoxcarsAI/boxcars#64]
Vector search is good for capturing semantically similar texts, but other systems are adding the ability to store meta data with each vector that can be used in union with the vector search to find things.

@jaigouk - since you wrote the vector store, is this concept there already, or can it be added with a little work?

**Comment by obie** [comment]
Marqo is great for this. Can include a filter expression in the query to scope the search down to certain end users, for instance.

**Comment by jaigouk** [comment]
@francis 
something like this? https://github.com/jaigouk/boxcars/blob/feature/add-in-memory-vector-store/lib/boxcars/boxcar/vector_stores/document.rb

```
class Document
      attr_accessor :page_content, :metadata

      def initialize(fields = {})
        @page_content = fields[:page_content] || ""
        @metadata = fields[:metadata] || {}
      end
      ```

**Comment by francis** [comment]
Yes, I think this is on the right path @jaigouk

**Comment by francis** [comment]
@obie - I will see what I can learn about Marqo. Thank you for the pointer.

**Comment by jaigouk** [comment]
@francis yup. 

I will continue https://github.com/BoxcarsAI/boxcars/issues/60 
I also want to clean up hnswlib based codes.

**Comment by francis** [comment]
@jaigouk also, I closed the ticket already, but I changed VectorStores to VectorStore and moved as a top-level peer to a Boxcar, Train, and Engine. I hope that doesn't mess up your tree too much.

**Comment by francis** [comment]
It looks like the VectorSearch PR might be some or all of this ticket. I think we want to filter results based on metadata and I can do this after the search. Is it possible to refine the search possibilities before searching?

**Comment by jaigouk** [comment]
vector search will return Document array based on distances. and the document instance has metadata method that returns the orignal hash if there were some. I am not injecting much info within metadata. the order of array is based on distance or similarity already. So I thought that it is upto users of this gem to "filter" the result further.

**Comment by jaigouk** [comment]
I thought about creating a demo app with hanami v2. and then even though I create a crawler, i may want to use the metadata for navigating the website structure. i guess we might need extra boxcar for crawlers. I might need to investigate for combining that with vector storage.
