### ISSUE TITLE
add PgVector Vector Store

### ISSUE THREAD

**Issue by francis** [BoxcarsAI/boxcars#68]

**Comment by jaigouk** [comment]
I guess https://github.com/ankane/neighbor is the fastest way to add pgvector to activerecord 

I was not able to find a compatible gem for rom.rb so I created https://github.com/jaigouk/rom-neighbor but it is more like a place holder as of now.

**Comment by francis** [comment]
That would be fine for Active Record.

I am also trying to keep things running from just Ruby without Active Record. I think this should be possible to follow how you build the current vector store. Does that seem possible to you?

**Comment by jaigouk** [comment]
https://github.com/pgvector/pgvector-ruby would be the gem to focus for that case in my opinion.

[adding cube and vector types was not straight forward and then i postponed to continue for rom-sql ](https://github.com/jaigouk/rom-neighbor/commit/e6046165a54d0e715fe2667fbf296af2d3a5b131#diff-ff371cf65dcf41bb74f8b3005cdb8e8634fd0366058b833f06c00bb2756e3a4eR9)

**Comment by francis** [comment]
Ok @jaigouk let me know if I can help in some way.

**Comment by jaigouk** [comment]
https://github.com/BoxcarsAI/boxcars/pull/80 is ready for review
