### ISSUE TITLE
Reg: User account specific / Support multi-tenancy

### ISSUE THREAD

**Issue by bazooka720** [BoxcarsAI/boxcars#77]
This is a great library and wondering if you can support multi-tenancy? If we have various tenants and each tenant has users. How to enable the functionality to be scoped to the user (rather than as admin)

**Comment by francis** [comment]
We would be glad to consider this. Tell me more about where you would like to see support for this. In the ActiveRecord boxcar?

**Comment by bazooka720** [comment]
@francis Thoughts on this?

**Comment by francis** [comment]
Let me make sure this works and get back to you, but I think you can pass the user id in as context.

**Comment by francis** [comment]
It doesn't quite work yet. I'm planning on changing the ActiveRecord boxcar to take additional context and use it in the prompt. I believe your use case would be solved with this.

**Comment by bazooka720** [comment]
Thanks a lot @francis

**Comment by erlingur** [comment]
@francis Was this completed? Also looking for this but I can't see how to accomplish this in the docs?
