### ISSUE TITLE
check Chroma as a vector store

### ISSUE THREAD

**Issue by jaigouk** [BoxcarsAI/boxcars#78]
I found [chroma](https://docs.trychroma.com/embeddings#default-sentence-transformers) is used for various tools like [privateGPT](https://github.com/imartinez/privateGPT) and discovered [chroma gem](https://github.com/mariochavez/chroma). 
But the gem supports only ruby v3.2.

I think it's worth to check

here is [the notebook](https://github.com/mariochavez/chroma/blob/main/notebook/Chroma%20Gem.ipynb)

**Comment by francis** [comment]
This looks interesting @jaigouk

**Comment by jaigouk** [comment]
2 other vector stores that i wish to check 

- https://faiss.ai/
- https://github.com/milvus-io/milvus
