### ISSUE TITLE
VectorAnswer boxcar should support all vector stores

### ISSUE THREAD

**Issue by francis** [BoxcarsAI/boxcars#84]
@jaigouk pointed this out in the review. The VectorAnswer boxcar should support all types of vector stores we define.

I think the best way to handle this is to create a new object that understands the vector store and how to make queries.

"please check spec/boxcars/vector_search_spec.rb for this. because we have multiple ways for vector stores, the configuration may differ."

**Comment by jaigouk** [comment]
I will look into this in this weekend @francis

**Comment by francis** [comment]
Anything I can do to help here @jaigouk?

**Comment by jaigouk** [comment]
sorry, i was away i will try this again in this weekend
