### ISSUE TITLE
Readme vector search example 404

### ISSUE THREAD

**Issue by beouk** [BoxcarsAI/boxcars#86]
Readme example for vector search goes to: https://github.com/BoxcarsAI/boxcars/blob/main/notebooks/vector_store_examples.ipynb

The correct URl is now: 
https://github.com/BoxcarsAI/boxcars/blob/main/notebooks/vector_search_examples.ipynb

**Comment by jaigouk** [comment]
Thanks for checking this out. 
I will update this. https://github.com/jaigouk/boxcars/pull/2

**Comment by francis** [comment]
@jaigouk - would you push this to me as a PR please? 🙏

**Comment by jaigouk** [comment]
@francis  opened a PR, because there were some issues I found, It took some time. https://github.com/BoxcarsAI/boxcars/pull/92 the PR is ready for review.
